server {
    listen 80;
    server_name _;  # замени на свой домен

    # Главное - все запросы, кроме API, идут на фронт
        location / {
            try_files $uri $uri/ /index.html;
        }

        # API запросы
        location /api {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Sanctum CSRF
        location /sanctum {
            try_files $uri $uri/ /index.php?$query_string;
        }

    # PHP запросы
    location ~ \.php$ {
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public$fastcgi_script_name;
    }

    # WebSocket для Reverb
    location /app {
        proxy_pass http://reverb:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}